<?php
/**
 * Plugin Name: Author Adsense
 * Plugin URI: https://tedliou.com
 * Description: Each author can earn his own advertising revenue.
 * Author: Ted Liou
 * Author URI: https://tedliou.com
 * Version: 1.0.0
 * License: GPL2+
 * License URI: http://www.gnu.org/licenses/gpl-2.0.txt
 */
 
defined( 'ABSPATH' ) or die();




/**
 * SHORTCODE
 */
function aad_shortcode() {
	$author_adsense_options = get_option( 'author_adsense_option_name' ); // Array of All Options
	$publisher_id_0 = $author_adsense_options['publisher_id_0']; // Publisher ID
	$slot_id_1 = $author_adsense_options['slot_id_1']; // Slot ID
	$user_publisher_id = get_user_meta(get_the_author_meta('ID'), 'aad-publisher-id', true);
	$user_slot_id = get_user_meta(get_the_author_meta('ID'), 'aad-slot-id', true);
?>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-<?php echo empty($user_publisher_id) ? $publisher_id_0 : $user_publisher_id; ?>"
     data-ad-slot="<?php echo empty($user_slot_id) ? $slot_id_1 : $user_slot_id; ?>"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
<?php
}
add_shortcode( 'aad', 'aad_shortcode' );




/**
 * USER VALUE
 */
function aad_usermeta_form( $user )
{
?>
<h3><?= __('Adsense Info', 'aad'); ?></h3>
<table class="form-table">
	<tr>
		<th>
			<label for="aad-publisher-id"><?= __('Publisher ID', 'aad'); ?></label>
		</th>
		<td>
			<input type="text"
				   class="regular-text"
				   id="aad-publisher-id"
				   name="aad-publisher-id"
				   value="<?= esc_attr( get_user_meta($user->ID, 'aad-publisher-id', true) ) ?>"
				   placeholder="pub-xxxxxxxxxxxxxxxx">
			<p class="description">
				<?= __('Please enter your publisher id.', 'aad'); ?>
			</p>
		</td>
	</tr>
	<tr>
		<th>
			<label for="aad-slot-id"><?= __('Slot ID', 'aad'); ?></label>
		</th>
		<td>
			<input type="text"
				   class="regular-text"
				   id="aad-slot-id"
				   name="aad-slot-id"
				   value="<?= esc_attr( get_user_meta($user->ID, 'aad-slot-id', true ) ) ?>"
				   placeholder="xxxxxxxxxx">
			<p class="description">
				<?= __('Please enter your slot id.', 'aad'); ?>
			</p>
		</td>
	</tr>
</table>
<?php
}
add_action( 'show_user_profile', 'aad_usermeta_form' );
add_action( 'edit_user_profile', 'aad_usermeta_form' );

function aad_usermeta_form_update( $user_id )
{
    if ( ! current_user_can( 'edit_user', $user_id ) ) {
        return false;
    }
	
	update_user_meta(
        $user_id,
        'aad-publisher-id',
        $_POST['aad-publisher-id']
    );
	
	update_user_meta(
        $user_id,
        'aad-slot-id',
        $_POST['aad-slot-id']
    );
  
    return;
}
add_action( 'personal_options_update', 'aad_usermeta_form_update' );
add_action( 'edit_user_profile_update', 'aad_usermeta_form_update' );




/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class AuthorAdsense {
	private $author_adsense_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'author_adsense_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'author_adsense_page_init' ) );
	}

	public function author_adsense_add_plugin_page() {
		add_options_page(
			'Author Adsense', // page_title
			'Author Adsense', // menu_title
			'manage_options', // capability
			'author-adsense', // menu_slug
			array( $this, 'author_adsense_create_admin_page' ) // function
		);
	}

	public function author_adsense_create_admin_page() {
		$this->author_adsense_options = get_option( 'author_adsense_option_name' ); ?>

		<div class="wrap">
			<h2>Author Adsense</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'author_adsense_option_group' );
					do_settings_sections( 'author-adsense-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function author_adsense_page_init() {
		register_setting(
			'author_adsense_option_group', // option_group
			'author_adsense_option_name', // option_name
			array( $this, 'author_adsense_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'author_adsense_setting_section', // id
			'Default Adsense Publisher', // title
			array( $this, 'author_adsense_section_info' ), // callback
			'author-adsense-admin' // page
		);

		add_settings_field(
			'publisher_id_0', // id
			'Publisher ID', // title
			array( $this, 'publisher_id_0_callback' ), // callback
			'author-adsense-admin', // page
			'author_adsense_setting_section' // section
		);

		add_settings_field(
			'slot_id_1', // id
			'Slot ID', // title
			array( $this, 'slot_id_1_callback' ), // callback
			'author-adsense-admin', // page
			'author_adsense_setting_section' // section
		);
	}

	public function author_adsense_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['publisher_id_0'] ) ) {
			$sanitary_values['publisher_id_0'] = sanitize_text_field( $input['publisher_id_0'] );
		}

		if ( isset( $input['slot_id_1'] ) ) {
			$sanitary_values['slot_id_1'] = sanitize_text_field( $input['slot_id_1'] );
		}

		return $sanitary_values;
	}

	public function author_adsense_section_info() {
		
	}

	public function publisher_id_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="author_adsense_option_name[publisher_id_0]" id="publisher_id_0" value="%s">',
			isset( $this->author_adsense_options['publisher_id_0'] ) ? esc_attr( $this->author_adsense_options['publisher_id_0']) : ''
		);
	}

	public function slot_id_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="author_adsense_option_name[slot_id_1]" id="slot_id_1" value="%s">',
			isset( $this->author_adsense_options['slot_id_1'] ) ? esc_attr( $this->author_adsense_options['slot_id_1']) : ''
		);
	}

}
if ( is_admin() )
	$author_adsense = new AuthorAdsense();

/* 
 * Retrieve this value with:
 * $author_adsense_options = get_option( 'author_adsense_option_name' ); // Array of All Options
 * $publisher_id_0 = $author_adsense_options['publisher_id_0']; // Publisher ID
 * $slot_id_1 = $author_adsense_options['slot_id_1']; // Slot ID
 */
